CREATE TABLE "accounts" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_name" varchar NOT NULL,
  "balance" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "currency" varchar
);

CREATE TABLE "entries" (
  "id" integer PRIMARY KEY,
  "account_id" int NOT NULL,
  "amount" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "transfers" (
  "id" integer PRIMARY KEY,
  "from_account" int NOT NULL,
  "to_account" int NOT NULL,
  "amount" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ON "accounts" ("owner_name");
CREATE INDEX ON "entries" ("account_id");
CREATE INDEX ON "transfers" ("from_account");
CREATE INDEX ON "transfers" ("to_account");
CREATE INDEX ON "transfers" ("from_account", "to_account");

ALTER TABLE "entries" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("user_id");
ALTER TABLE "transfers" ADD FOREIGN KEY ("from_account") REFERENCES "accounts" ("user_id");
ALTER TABLE "transfers" ADD FOREIGN KEY ("to_account") REFERENCES "accounts" ("user_id");