// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  owner_name,
  balance,
  currency
) VALUES (
  $1, $2 ,$3
)
RETURNING user_id, owner_name, balance, created_at, currency
`

type CreateAccountParams struct {
	OwnerName string         `json:"owner_name"`
	Balance   int64          `json:"balance"`
	Currency  sql.NullString `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount, arg.OwnerName, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.UserID,
		&i.OwnerName,
		&i.Balance,
		&i.CreatedAt,
		&i.Currency,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts 
WHERE user_id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, userID int32) error {
	_, err := q.exec(ctx, q.deleteAccountStmt, deleteAccount, userID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT user_id, owner_name, balance, created_at, currency FROM accounts
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, userID int32) (Account, error) {
	row := q.queryRow(ctx, q.getAccountStmt, getAccount, userID)
	var i Account
	err := row.Scan(
		&i.UserID,
		&i.OwnerName,
		&i.Balance,
		&i.CreatedAt,
		&i.Currency,
	)
	return i, err
}

const listAccount = `-- name: ListAccount :many
SELECT user_id, owner_name, balance, created_at, currency FROM accounts
ORDER BY user_id
LIMIT $1
OFFSET $2
`

type ListAccountParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error) {
	rows, err := q.query(ctx, q.listAccountStmt, listAccount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.UserID,
			&i.OwnerName,
			&i.Balance,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET balance = $2
WHERE user_id = $1
RETURNING user_id, owner_name, balance, created_at, currency
`

type UpdateAccountParams struct {
	UserID  int32 `json:"user_id"`
	Balance int64 `json:"balance"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.exec(ctx, q.updateAccountStmt, updateAccount, arg.UserID, arg.Balance)
	return err
}
