// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Account struct {
	UserID    int32          `json:"user_id"`
	OwnerName string         `json:"owner_name"`
	Balance   int64          `json:"balance"`
	CreatedAt sql.NullTime   `json:"created_at"`
	Currency  sql.NullString `json:"currency"`
}

type Entry struct {
	ID        int32        `json:"id"`
	AccountID int32        `json:"account_id"`
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	ID          int32        `json:"id"`
	FromAccount int32        `json:"from_account"`
	ToAccount   int32        `json:"to_account"`
	Amount      int64        `json:"amount"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
